project:
  type: website
  output-dir: docs

website:
  title: "Sunwoo Kwak's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - CV.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



